// Generated by generate.mjs: this package's API on each marketplace.
export const API_TITLE = 'Social Links Finder for Company Profiles';
export const API_MARKET_SLUG = 'social-links-finder';
export const RAPIDAPI_HOST = 'social-links-finder-for-company-profiles.p.rapidapi.com';
