// Generated by generate.mjs: this package's API on each marketplace.
export const API_TITLE = 'Phone Number Validator and Formatter';
export const API_MARKET_SLUG = 'phone-validator';
export const RAPIDAPI_HOST = 'phone-number-validator-and-formatter1.p.rapidapi.com';
