// Generated by generate.mjs: this package's API on each marketplace.
export const API_TITLE = 'Article Extractor to Clean Text and Markdown';
export const API_MARKET_SLUG = 'article-extractor';
export const RAPIDAPI_HOST = 'article-extractor-to-clean-text-and-markdown.p.rapidapi.com';
