// Generated by generate.mjs: each resource's API on each marketplace.
export const API_MARKET_SLUGS: Record<string, string> = {
	"holiday": "public-holidays",
	"email": "email-validator",
	"phone": "phone-validator",
	"article": "article-extractor",
	"linkPreview": "link-preview",
	"contact": "contact-extractor",
	"socialLinks": "social-links-finder",
	"techStack": "tech-stack-detector",
	"code": "qr-barcode",
	"pdf": "pdf-to-text"
};
export const RAPIDAPI_HOSTS: Record<string, string> = {
	"holiday": "public-holidays-and-business-days.p.rapidapi.com",
	"email": "email-validator-with-mx-and-disposable-check.p.rapidapi.com",
	"phone": "phone-number-validator-and-formatter1.p.rapidapi.com",
	"article": "article-extractor-to-clean-text-and-markdown.p.rapidapi.com",
	"linkPreview": "link-preview-and-url-metadata2.p.rapidapi.com",
	"contact": "website-contact-extractor-for-emails-and-phones.p.rapidapi.com",
	"socialLinks": "social-links-finder-for-company-profiles.p.rapidapi.com",
	"techStack": "website-technology-stack-detector.p.rapidapi.com",
	"code": "qr-code-and-barcode-generator-and-reader.p.rapidapi.com",
	"pdf": "pdf-to-text-and-markdown.p.rapidapi.com"
};
