// Generated by generate.mjs: this package's API on each marketplace.
export const API_TITLE = 'PDF to Text and Markdown';
export const API_MARKET_SLUG = 'pdf-to-text';
export const RAPIDAPI_HOST = 'pdf-to-text-and-markdown.p.rapidapi.com';
