// Generated by generate.mjs: this package's API on each marketplace.
export const API_TITLE = 'QR Code and Barcode Generator and Reader';
export const API_MARKET_SLUG = 'qr-barcode';
export const RAPIDAPI_HOST = 'qr-code-and-barcode-generator-and-reader.p.rapidapi.com';
